### ISSUE TITLE
jtree combine always fails with similar message

### ISSUE THREAD

**Issue by ghost** [treenotation/treebase#4]
node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:112
    if (!node) throw new Error(`No registered grammar named '${grammarName}'. Registered grammars are ${this._getRegisteredGrammarNames().join(",")}`)

NOTE: ADDED BY issue poster this line below, changes with the next (optional? ) argument to tree combine 
Error: No registered grammar named 'undefined'. Registered grammars are defaultRoot    
    at CommandLineApp._getGrammarPathByGrammarNameOrThrow (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:112:22)
    at CommandLineApp._history (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:202:10)
    at CommandLineApp.programs (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:182:17)
    at CommandLineApp.combine (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:41:26)
    at Function.main (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:315:40)
    at Object.<anonymous> (/home/coderz/Downloads/node-v16.17.0-linux-x64/lib/node_modules/jtree/products/commandLineApp.node.js:330:36)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)

**Comment by breck7** [comment]
removed combine for now
